dist: xenial
language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

env:
  matrix:
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=2.0
    - DJANGO_VERSION=1.11

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.1

install:
  - pip install tox coveralls

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//./}-dj${DJANGO_VERSION//./},coverage

# report coverage to coveralls.io
after_success: coveralls

notifications:
  slack: tobalabs:XPt5OlsKuFGgIQZp0DpNXBUl

jobs:
  include:
    - stage: pypi release
      if: tag IS present
      python: "3.6"
      script: echo "Deploying to pypi ..."
      deploy:
        provider: pypi
        user: mwarkentin
        password:
          secure: "cQtAP8fMu+KzfBKG3ibTTXmDGZuz/FBp8RrLI8ddMGV4Jj5ElZLsvbqU43fiHbtVPV/uALDPF76WNGlpRH1P4w9m4XrFNCvkrnjtwIk7NZWi7uubWZcqQk9VE7MTP+i2IYrtNlGmlq1dbdJZcwS0mdzJcAAhAaP830Ekmqws9xE="
        distributions: "sdist bdist_wheel"
        on:
          tags: true
