# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.7
  - DJANGO_VERSION=1.9.0

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source watchman runtests.py

# report coverage to coveralls.io
after_success: coveralls

notifications:
  slack: tobalabs:XPt5OlsKuFGgIQZp0DpNXBUl
